---
- name: Verify and install ec2-instance-connect
  hosts: all
  become: yes
  tasks:
    - name: Determine OS type
      command: cat /etc/os-release
      register: os_release

    - name: Set OS family fact
      set_fact:
        os_family: "{{ 'Debian' if 'ubuntu' in os_release.stdout.lower() else 'RedHat' if 'amzn' in os_release.stdout.lower() else 'Unknown' }}"

    - name: Check if ec2-instance-connect is installed (Ubuntu)
      command: dpkg -l | grep ec2-instance-connect
      register: ec2_instance_connect_installed_ubuntu
      ignore_errors: yes
      when: os_family == "Debian"

    - name: Check if ec2-instance-connect is installed (Amazon Linux)
      command: rpm -qa | grep ec2-instance-connect
      register: ec2_instance_connect_installed_amazon
      ignore_errors: yes
      when: os_family == "RedHat"

    - name: Install ec2-instance-connect (Ubuntu)
      shell: |
        sudo apt-get update
        sudo apt-get install -y ec2-instance-connect
      when: os_family == "Debian" and ec2_instance_connect_installed_ubuntu.rc != 0

    - name: Install ec2-instance-connect (Amazon Linux)
      shell: |
        sudo yum install -y ec2-instance-connect
      when: os_family == "RedHat" and ec2_instance_connect_installed_amazon.rc != 0

    - name: Verify installation of ec2-instance-connect (Ubuntu)
      command: dpkg -l | grep ec2-instance-connect
      register: verify_installation_ubuntu
      when: os_family == "Debian"

    - name: Verify installation of ec2-instance-connect (Amazon Linux)
      command: rpm -qa | grep ec2-instance-connect
      register: verify_installation_amazon
      when: os_family == "RedHat"

    - name: Debug output (Ubuntu)
      debug:
        msg: "ec2-instance-connect installation result (Ubuntu): {{ verify_installation_ubuntu }}"
      when: os_family == "Debian"

    - name: Debug output (Amazon Linux)
      debug:
        msg: "ec2-instance-connect installation result (Amazon Linux): {{ verify_installation_amazon }}"
      when: os_family == "RedHat"
